security:

    encoders:
        Rscine\AppBundle\Security\User\RscineApiUser: plaintext

    providers:
        in_memory:
            memory: ~
        rscine:
            id: rscine_app.security.user_provider.rscine_api

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            form_login:
                provider: rscine
                login_path: login
                check_path: login_check

    access_control:
        - { path: ^/(login|register)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
